version: 0.2

phases:
  install:
    commands:
      - echo "Installing semgrep..."
      - python -m pip install --upgrade pip
      - pip install semgrep

  pre_build:
    commands:
      - echo "Running Semgrep scan..."
      - semgrep ci

  build:
    commands:
      - echo "Entering the build phases"

post_build:
  commands:
    - echo "Build done"
